// Root Layout, 即使手動刪除也會再自動生成，須從 html tag 開始撰寫
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightBlue", padding: "1rem" }}>Header</header>
        {children}
        <footer style={{ backgroundColor: "ghostWhite", padding: "1rem" }}>Footer</footer>
      </body>
    </html>
  );
}
