// Root Layout, 即使手動刪除也會再自動生成，須從 html tag 開始撰寫

import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.ts Tutorial",
    template: "%s | Next.ts Tutorial", // 子路由才會套用 template，當前頁面不會
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightBlue", padding: "1rem" }}>Header</header>
        {children}
        <footer style={{ backgroundColor: "ghostWhite", padding: "1rem" }}>Footer</footer>
      </body>
    </html>
  );
}
